drop table if exists adventuring_gear;

create table adventuring_gear(name char(30) not null unique, weight float not null, max_number int null,
type char(14) null);

insert into adventuring_gear (name, weight) values('Abacus', 2);
insert into adventuring_gear (name, weight) values('Acid (vial)', 1);
insert into adventuring_gear (name, weight) values('Alchemist''s fire (flask)', 1);
insert into adventuring_gear (name, weight, max_number, type) values('Arrows', 1, 20, 'Ammunition');
insert into adventuring_gear (name, weight, max_number, type) values('Blowgun needles', 1, 50, 'Ammunition');
insert into adventuring_gear (name, weight, max_number, type) values('Crossbow bolts', 1.5, 20, 'Ammunition');
insert into adventuring_gear (name, weight, max_number, type) values('Sling bullets', 1.5, 20, 'Ammunition');
insert into adventuring_gear (name, weight, type) values('Antitoxin (vial)', 0.05, null);
insert into adventuring_gear (name, weight, type) values('Crystal', 1, 'Arcane focus');
insert into adventuring_gear (name, weight, type) values('Orb', 3, 'Arcane focus');
insert into adventuring_gear (name, weight, type) values('Rod', 2, 'Arcane focus');
insert into adventuring_gear (name, weight, type) values('Staff', 4, 'Arcane focus');
insert into adventuring_gear (name, weight, type) values('Wand', 1, 'Arcane focus');
insert into adventuring_gear (name, weight) values('Backpack', 5);
insert into adventuring_gear (name, weight, max_number) values('Ball bearings (bag )', 2, 1000);
insert into adventuring_gear (name, weight) values('Barrel', 70);
insert into adventuring_gear (name, weight) values('Basket', 2);
insert into adventuring_gear (name, weight) values('Block and tackle', 5);
insert into adventuring_gear (name, weight) values('Book', 5);
insert into adventuring_gear (name, weight) values('Bedroll', 7);
insert into adventuring_gear (name, weight) values('Bell', 0.05);
insert into adventuring_gear (name, weight) values('Blanket', 3);
insert into adventuring_gear (name, weight) values('Bottle, glass', 2);
insert into adventuring_gear (name, weight) values('Bucket', 2);
insert into adventuring_gear (name, weight,  max_number) values('Caltrops (bag)', 2, 20);
insert into adventuring_gear (name, weight) values('Candle', 0.05);
insert into adventuring_gear (name, weight) values('Case, crossbow bolt', 1);
insert into adventuring_gear (name, weight) values('Case, map or scroll', 1);
insert into adventuring_gear (name, weight) values('Chain (10 feet)', 10);
insert into adventuring_gear (name, weight) values('Chalk (1 piece)', 0.05);
insert into adventuring_gear (name, weight) values('Chest', 25);
insert into adventuring_gear (name, weight) values('Climber''s kit', 12);
insert into adventuring_gear (name, weight) values('Clothes, common', 3);
insert into adventuring_gear (name, weight) values('Clothes, costume', 4);
insert into adventuring_gear (name, weight) values('Clothes, fine', 6);
insert into adventuring_gear (name, weight) values('Clothes, traveler''s', 4);
insert into adventuring_gear (name, weight) values('Component pouch', 2);
insert into adventuring_gear (name, weight) values('Crowbar', 5);
insert into adventuring_gear (name, weight, type) values('Sprig of mistletoe', 0.05, 'Druidic focus');
insert into adventuring_gear (name, weight, type) values('Totem', 0.01, 'Druidic focus');
insert into adventuring_gear (name, weight, type) values('Wooden staff', 4, 'Druidic focus');
insert into adventuring_gear (name, weight, type) values('Yew wand', 1, 'Druidic focus');
insert into adventuring_gear (name, weight) values('Fishing tackle', 4);
insert into adventuring_gear (name, weight) values('Flask or tankard', 1);
insert into adventuring_gear (name, weight) values('Grappling hook', 4);
insert into adventuring_gear (name, weight) values('Hammer', 3);
insert into adventuring_gear (name, weight) values('Hammer, sledge', 10);
insert into adventuring_gear (name, weight) values('Healer''s kit', 3);
insert into adventuring_gear (name, weight, type) values('Amulet', 1, 'Holy symbol');
insert into adventuring_gear (name, weight, type) values('Emblem', 0.01, 'Holy symbol');
insert into adventuring_gear (name, weight, type) values('Reliquary', 2, 'Holy symbol');
insert into adventuring_gear (name, weight) values('Holy water (flask)', 1);
insert into adventuring_gear (name, weight) values('Hourglass', 1);
insert into adventuring_gear (name, weight) values('Hunting trap', 25);
insert into adventuring_gear (name, weight) values('Ink (1 ounce bottle)', 0.1);
insert into adventuring_gear (name, weight) values('Ink pen', 0);
insert into adventuring_gear (name, weight) values('Jug or pitcher', 4);
insert into adventuring_gear (name, weight) values('Ladder (10-foot)', 25);
insert into adventuring_gear (name, weight) values('Lamp', 1);
insert into adventuring_gear (name, weight) values('Lantern, bullseye', 2);
insert into adventuring_gear (name, weight) values('Lantern, hooded', 2);
insert into adventuring_gear (name, weight) values('Lock', 1);
insert into adventuring_gear (name, weight) values('Magnifying glass', 0.05);
insert into adventuring_gear (name, weight) values('Manacles', 6);
insert into adventuring_gear (name, weight) values('Mess kit', 1);
insert into adventuring_gear (name, weight) values('Mirror, steel', 0.5);
insert into adventuring_gear (name, weight) values('Oil (flask)', 1);
insert into adventuring_gear (name, weight) values('Paper (one sheet)', 0.01);
insert into adventuring_gear (name, weight) values('Parchment (one sheet)', 0.01);
insert into adventuring_gear (name, weight) values('Perfume (vial)', 0.05);
insert into adventuring_gear (name, weight) values('Pick, miner''s', 10);
insert into adventuring_gear (name, weight) values('Piton', 0.25);
insert into adventuring_gear (name, weight) values('Poison, basic (vial)', 0.1);
insert into adventuring_gear (name, weight) values('Pole (10-foot)', 7);
insert into adventuring_gear (name, weight) values('Pot, iron', 10);
insert into adventuring_gear (name, weight) values('Potion of healing', 0.5);
insert into adventuring_gear (name, weight) values('Pouch', 1);
insert into adventuring_gear (name, weight) values('Quiver', 1);
insert into adventuring_gear (name, weight) values('Ram, portable', 35);
insert into adventuring_gear (name, weight) values('Rations (1 day)', 2);
insert into adventuring_gear (name, weight) values('Robes', 4);
insert into adventuring_gear (name, weight) values('Rope, hempen (50 feet)', 10);
insert into adventuring_gear (name, weight) values('Rope, silk (50 feet)', 5);
insert into adventuring_gear (name, weight) values('Sack', 0.5);
insert into adventuring_gear (name, weight) values('Scale, merchant''s', 3);
insert into adventuring_gear (name, weight) values('Sealing wax', 0.05);
insert into adventuring_gear (name, weight) values('Shovel', 5);
insert into adventuring_gear (name, weight) values('Signal whistle', 0.05);
insert into adventuring_gear (name, weight) values('Signet ring', 0.01);
insert into adventuring_gear (name, weight) values('Soap', 0.1);
insert into adventuring_gear (name, weight) values('Spellbook', 3);
insert into adventuring_gear (name, weight, max_number) values('Spikes, iron ', 5, 10);
insert into adventuring_gear (name, weight) values('Spyglass', 1);
insert into adventuring_gear (name, weight) values('Tent, two-person', 20);
insert into adventuring_gear (name, weight) values('Torch', 1);
insert into adventuring_gear (name, weight) values('Vial', .01);
insert into adventuring_gear (name, weight) values('Waterskin (full)', 5);
insert into adventuring_gear (name, weight) values('Whetstone', 1);

select  * from adventuring_gear;
